# -*- coding: utf-8 -*-
"""AdapterA_notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWlyxHbdHicSwjQHPU4duJTQlCrbsX9x
"""

!pip install -q transformers datasets peft accelerate bitsandbytes evaluate rouge_score sacrebleu

!pip uninstall -y bitsandbytes
!pip install -U bitsandbytes>=0.46.1
!pip install -U transformers accelerate peft

from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/jsonl_for_txt.zip"

OUT_DIR = "/content/drive/MyDrive/medgemma_a100_lora_run"

import os
from datasets import load_dataset, concatenate_datasets

base_path = "/content/jsonl_for_txt"

file_category_map = {
    # Thyroid
    "dataset_hypo.jsonl": "thyroid",
    "dataset_hypo_bal.jsonl": "thyroid",

    # PCOS
    "pcos_medgemma_multitask.jsonl": "pcos",
    "pcos_medgemma_task.jsonl": "pcos",
    "pcos1.jsonl": "pcos",
    "pcoss_sur.jsonl": "pcos",

    # Endometriosis
    "task1_hormonal_morphologic_endometriosis (1).jsonl": "endometriosis",
    "task2_reproductive_endometriosis_probability.jsonl": "endometriosis",

    # Anemia
    "female_anemia_multi_template.jsonl": "anemia",

    # Gestational Diabetes
    "gestational_diabetes_medgemma (1).jsonl": "gestational_diabetes_risk",

    # Preeclampsia
    "preeclampsia_bp.jsonl": "preeclampsia_risk",

    # Menses Pattern
    "task_menses_pattern (1).jsonl": "menses_pattern",
    "task1_menses_pattern (1).jsonl": "menses_pattern",

    # Education
    "task3_menstrual_education (1).jsonl": "menses_awareness",
    "remedial_symptom_awaren.jsonl": "menses_awareness",
    "remedial_symptom_awaren (1).jsonl": "menses_awareness",

    # Risk / Recurrence (we classify under risk)
    "dataset1_risk.jsonl": "thyroid",
    "dataset1_recurrence.jsonl": "thyroid",

    # Hormone ratio (likely endocrine)
    "dataset_ratio.jsonl": "thyroid"
}

datasets_list = []

for file_name, category in file_category_map.items():
    path = os.path.join(base_path, file_name)

    if os.path.exists(path):
        ds = load_dataset("json", data_files=path)["train"]
        ds = ds.add_column("category", [category] * len(ds))
        datasets_list.append(ds)
        print(f"Loaded {file_name} → {category} ({len(ds)} samples)")
    else:
        print(f"File not found: {file_name}")

full_dataset = concatenate_datasets(datasets_list)

print("\nTotal merged samples:", len(full_dataset))

from collections import Counter
print("\nCategory distribution:")
print(Counter(full_dataset["category"]))

# Define category groups
adapterA_categories = [
    "thyroid",
    "pcos",
    "anemia",
    "endometriosis"
]

adapterB_categories = [
    "gestational_diabetes_risk",
    "preeclampsia_risk",
    "menses_pattern",
    "menses_awareness"
]

# Filter datasets
adapterA_dataset = full_dataset.filter(
    lambda x: x["category"] in adapterA_categories
)

adapterB_dataset = full_dataset.filter(
    lambda x: x["category"] in adapterB_categories
)

from collections import Counter

print("Adapter A distribution:")
print(Counter(adapterA_dataset["category"]))

print("\nAdapter B distribution:")
print(Counter(adapterB_dataset["category"]))

print("\nAdapter A size:", len(adapterA_dataset))
print("Adapter B size:", len(adapterB_dataset))

from datasets import Dataset
import random

random.seed(42)

target_size = 10000

balanced_splits = []

for category in adapterA_categories:
    subset = adapterA_dataset.filter(lambda x: x["category"] == category)
    current_size = len(subset)

    print(f"{category} original size: {current_size}")

    if current_size > target_size:
        # Downsample
        subset = subset.shuffle(seed=42).select(range(target_size))

    elif current_size < target_size:
        # Oversample
        multiplier = target_size // current_size
        remainder = target_size % current_size

        oversampled = concatenate_datasets([subset] * multiplier)
        if remainder > 0:
            oversampled = concatenate_datasets([
                oversampled,
                subset.shuffle(seed=42).select(range(remainder))
            ])
        subset = oversampled

    print(f"{category} balanced size: {len(subset)}\n")
    balanced_splits.append(subset)

balanced_adapterA = concatenate_datasets(balanced_splits)

print("Final Balanced Adapter A Distribution:")
print(Counter(balanced_adapterA["category"]))
print("Total Balanced Size:", len(balanced_adapterA))

target_size_B = 2000

balanced_splits_B = []

for category in adapterB_categories:
    subset = adapterB_dataset.filter(lambda x: x["category"] == category)
    current_size = len(subset)

    print(f"{category} original size: {current_size}")

    if current_size > target_size_B:
        subset = subset.shuffle(seed=42).select(range(target_size_B))

    elif current_size < target_size_B:
        multiplier = target_size_B // current_size
        remainder = target_size_B % current_size

        oversampled = concatenate_datasets([subset] * multiplier)
        if remainder > 0:
            oversampled = concatenate_datasets([
                oversampled,
                subset.shuffle(seed=42).select(range(remainder))
            ])
        subset = oversampled

    print(f"{category} balanced size: {len(subset)}\n")
    balanced_splits_B.append(subset)

balanced_adapterB = concatenate_datasets(balanced_splits_B)

print("Final Balanced Adapter B Distribution:")
print(Counter(balanced_adapterB["category"]))
print("Total Balanced Size:", len(balanced_adapterB))

from datasets import Features, ClassLabel
import random

random.seed(42)
unique_categories = balanced_adapterA.unique("category")
balanced_adapterA = balanced_adapterA.cast_column(
    "category", ClassLabel(names=sorted(unique_categories))
)

adapterA_split = balanced_adapterA.train_test_split(
    test_size=0.1,
    seed=42,
    stratify_by_column="category"
)

train_A = adapterA_split["train"]
val_A = adapterA_split["test"]

print("Adapter A train size:", len(train_A))
print("Adapter A val size:", len(val_A))

print(train_A[0])

from datasets import Features, ClassLabel

unique_categories_b = balanced_adapterB.unique("category")
balanced_adapterB = balanced_adapterB.cast_column(
    "category", ClassLabel(names=sorted(unique_categories_b))
)

adapterB_split = balanced_adapterB.train_test_split(
    test_size=0.1,
    seed=42,
    stratify_by_column="category"
)

train_B = adapterB_split["train"]
val_B = adapterB_split["test"]

print("Adapter B train size:", len(train_B))
print("Adapter B val size:", len(val_B))

print(train_B[0])

def format_example(example):
    if example["input"].strip() != "":
        text = f"""### Instruction:
{example['instruction']}

### Input:
{example['input']}

### Response:
{example['output']}"""
    else:
        text = f"""### Instruction:
{example['instruction']}

### Response:
{example['output']}"""
    return {"text": text}

train_A = train_A.map(format_example, remove_columns=train_A.column_names)
val_A = val_A.map(format_example, remove_columns=val_A.column_names)

print(train_A[0]["text"])

from huggingface_hub import login
import os

# Option 1: Use your HF token (get from https://huggingface.co/settings/tokens)
HF_TOKEN = "" # 
login(token=HF_TOKEN)

# Option 2: If token in env (Colab: add as secret)
# login(token=os.getenv("HF_TOKEN"))

import torch
from transformers import AutoProcessor, AutoModelForImageTextToText, BitsAndBytesConfig

model_id = "google/medgemma-4b-it"

bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,  # A100
    bnb_4bit_quant_storage=torch.uint8,     # saves VRAM
)

model = AutoModelForImageTextToText.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    attn_implementation="eager",
    quantization_config=bnb,
)

processor = AutoProcessor.from_pretrained(model_id)
processor.tokenizer.padding_side = "right"

# Key for training memory
model.config.use_cache = False

from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model

peft_config = LoraConfig(
    r=4,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    target_modules="all-linear",
    task_type="CAUSAL_LM",
    modules_to_save=None,
)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

from typing import Any

def collate_fn(examples: list[dict[str, Any]]):
    texts = [ex["text"].strip() for ex in examples]
    batch = processor(
        text=texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=512,
    )
    labels = batch["input_ids"].clone()
    labels[labels == processor.tokenizer.pad_token_id] = -100
    batch["labels"] = labels
    return batch

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir=OUT_DIR,

    # Let it run "forever" across sessions by resuming
    num_train_epochs=1,  # keep 1; you'll resume if interrupted

    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,  # effective batch 16

    gradient_checkpointing=True,
    optim="paged_adamw_8bit",

    bf16=True,
    fp16=False,

    learning_rate=2e-4,
    warmup_ratio=0.03,
    lr_scheduler_type="linear",
    max_grad_norm=0.3,

    logging_steps=20,

    # No eval for stability/compute
    eval_strategy="no",

    # THIS is what protects you from disconnect
    save_strategy="steps",
    save_steps=50,          # every ~50 steps
    save_total_limit=3,     # keep last 3 checkpoints only

    remove_unused_columns=False,
    label_names=["labels"],
    report_to=["tensorboard"],
    push_to_hub=False,
)

from transformers import Trainer
import os, glob

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_A,
    data_collator=collate_fn,
)

# Auto-resume if checkpoints exist
ckpts = sorted(glob.glob(os.path.join(OUT_DIR, "checkpoint-*")), key=lambda x: int(x.split("-")[-1]))
resume_path = ckpts[-1] if ckpts else None

trainer.train(resume_from_checkpoint=resume_path)

FINAL_DIR = "/content/drive/MyDrive/medgemma_a100_lora_adapter"
trainer.save_model(FINAL_DIR)
processor.tokenizer.save_pretrained(FINAL_DIR)

trainer.save_model("/content/drive/MyDrive/medgemma_a100_lora_adapter")
processor.tokenizer.save_pretrained("/content/drive/MyDrive/medgemma_a100_lora_adapter")

!zip -r medgemma_lora.zip /content/drive/MyDrive/medgemma_a100_lora_adapter

from google.colab import files
files.download("medgemma_lora.zip")

FINAL_DIR = "/content/drive/MyDrive/medgemma_a100_lora_adapter"
BASE_ID   = "google/medgemma-4b-it"

import torch, math
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

tokenizer = AutoTokenizer.from_pretrained(FINAL_DIR, use_fast=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

base = AutoModelForCausalLM.from_pretrained(
    BASE_ID,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True
)

model = PeftModel.from_pretrained(base, FINAL_DIR)
model.eval()

print("Loaded ✅")

import re
from torch.utils.data import DataLoader

RESPONSE_TAG = "### Response:\n"

def make_eval_features(batch, max_len=2048):
    input_ids_list, attn_list, labels_list = [], [], []

    for text in batch["text"]:
        # tokenize full text (prompt + output)
        enc = tokenizer(text, add_special_tokens=False, truncation=True, max_length=max_len)
        input_ids = enc["input_ids"]
        attn = enc["attention_mask"]

        # find where response starts in raw text
        idx = text.find(RESPONSE_TAG)
        if idx == -1:
            # if missing, just score everything (fallback)
            labels = input_ids.copy()
        else:
            prompt_text = text[: idx + len(RESPONSE_TAG)]
            prompt_ids = tokenizer(prompt_text, add_special_tokens=False).input_ids

            # mask prompt tokens with -100 so loss is only on response
            labels = [-100]*len(prompt_ids) + input_ids[len(prompt_ids):]

        # make sure same length
        labels = labels[:len(input_ids)]

        input_ids_list.append(torch.tensor(input_ids, dtype=torch.long))
        attn_list.append(torch.tensor(attn, dtype=torch.long))
        labels_list.append(torch.tensor(labels, dtype=torch.long))

    return {"input_ids": input_ids_list, "attention_mask": attn_list, "labels": labels_list}

def collate_pad(features):
    maxlen = max(f["input_ids"].shape[0] for f in features)

    def pad(x, value):
        return torch.nn.functional.pad(x, (0, maxlen - x.shape[0]), value=value)

    input_ids = torch.stack([pad(f["input_ids"], tokenizer.pad_token_id) for f in features])
    attention_mask = torch.stack([pad(f["attention_mask"], 0) for f in features])
    labels = torch.stack([pad(f["labels"], -100) for f in features])

    return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}

# Make a DataLoader from val_A
# val_A must have column "text"
batch_size = 2

def val_generator():
    for i in range(0, len(val_A), batch_size):
        batch = val_A[i:i+batch_size]
        feats = make_eval_features(batch)
        # convert list-of-tensors to list-of-dicts for collator
        items = []
        for j in range(len(feats["input_ids"])):
            items.append({k: feats[k][j] for k in feats})
        yield items

losses = []
with torch.no_grad():
    for items in val_generator():
        batch = collate_pad(items)
        batch = {k: v.to(model.device) for k, v in batch.items()}
        out = model(**batch)
        losses.append(out.loss.detach().float().item())

mean_loss = sum(losses) / len(losses)
ppl = math.exp(mean_loss) if mean_loss < 50 else float("inf")

print("Val samples:", len(val_A))
print("Val loss:", round(mean_loss, 4))
print("Val perplexity:", round(ppl, 3))

import random

def generate_response(instruction, inp="", max_new_tokens=350):
    instruction = (instruction or "").strip()
    inp = (inp or "").strip()

    if inp != "":
        prompt = f"""### Instruction:
{instruction}

### Input:
{inp}

### Response:
"""
    else:
        prompt = f"""### Instruction:
{instruction}

### Response:
"""

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        gen = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    txt = tokenizer.decode(gen[0], skip_special_tokens=True)
    return txt.split("### Response:", 1)[-1].strip()

# pick 5 first (then increase to 20)
for idx in random.sample(range(len(val_A)), 5):
    text = val_A[idx]["text"]
    # split your stored text into instruction/input/output
    # easiest: reconstruct by parsing
    # We'll just show gold + make a new prompt from same stored example.

    # GOLD (what the dataset expects)
    gold = text.split("### Response:\n", 1)[-1].strip()

    # Create prompt without the gold response:
    prompt_only = text.split("### Response:\n", 1)[0] + "### Response:\n"

    inputs = tokenizer(prompt_only, return_tensors="pt").to(model.device)
    with torch.no_grad():
        gen = model.generate(
            **inputs,
            max_new_tokens=350,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )
    pred_full = tokenizer.decode(gen[0], skip_special_tokens=True)
    pred = pred_full.split("### Response:", 1)[-1].strip()

    print("\n" + "="*50)
    print("PRED:\n", pred[:1200])
    print("\nGOLD:\n", gold[:1200])

import torch

def build_prompt(instruction, inp=""):
    instruction = (instruction or "").strip()
    inp = (inp or "").strip()
    if inp:
        return f"""### Instruction:
{instruction}

### Input:
{inp}

### Response:
"""
    else:
        return f"""### Instruction:
{instruction}

### Response:
"""

def generate_clean(instruction, inp="", max_new_tokens=180):
    # Hard constraint instruction (no retraining needed)
    instruction2 = instruction.strip() + "\n\nReturn ONLY the answer in the same format. Do not add extra definitions. Stop after the final line."

    prompt = build_prompt(instruction2, inp)
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,               # deterministic
            repetition_penalty=1.12,       # reduces looping
            no_repeat_ngram_size=4,        # helps stop repeated chunks
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    text = tokenizer.decode(out[0], skip_special_tokens=True)
    resp = text.split("### Response:", 1)[-1].strip()

    # Optional: post-clean (remove accidental reprints of Instruction/Input)
    cut_markers = ["### Instruction:", "### Input:"]
    for m in cut_markers:
        if m in resp:
            resp = resp.split(m, 1)[0].strip()

    return resp

import re

def sanitize_output(text, max_lines=30, max_chars=1800):
    # Trim huge rambles
    text = text.strip()[:max_chars]

    # Remove repeated identical lines (common looping)
    lines = [ln.rstrip() for ln in text.splitlines()]
    out = []
    seen = set()
    for ln in lines:
        key = ln.strip()
        if key and key in seen:
            continue
        if key:
            seen.add(key)
        out.append(ln)
        if len(out) >= max_lines:
            break
    return "\n".join(out).strip()

instruction = "Analyze the hormonal profile and provide structured reasoning without diagnosis."

inp = """FSH/LH ratio: 2.16
AMH: 5.2 ng/mL
Total Follicle Count: 18
BMI: 29
Waist-Hip Ratio: 0.91"""

resp = sanitize_output(generate_clean(instruction, inp))
print(resp)

##eval done





####heavy version before

import torch
from transformers import AutoProcessor, AutoModelForImageTextToText, BitsAndBytesConfig

model_id = "google/medgemma-4b-it"

# 1) dtype: prefer bf16 if supported, else fp16
major_cc, _ = torch.cuda.get_device_capability()
use_bf16 = major_cc >= 8
compute_dtype = torch.bfloat16 if use_bf16 else torch.float16

model_kwargs = dict(
    attn_implementation="eager",
    torch_dtype=compute_dtype,
    device_map="auto",
)

# 2) 4-bit quantization (QLoRA)
model_kwargs["quantization_config"] = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
)

# 3) Load model + processor (requires HF auth if gated)
model = AutoModelForImageTextToText.from_pretrained(model_id, **model_kwargs)
processor = AutoProcessor.from_pretrained(model_id)

# 4) Right padding is recommended for training stability
processor.tokenizer.padding_side = "right"

from peft import LoraConfig

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    target_modules="all-linear",
    task_type="CAUSAL_LM",
    modules_to_save=["lm_head", "embed_tokens"],
)

from typing import Any
import torch

def collate_fn(examples: list[dict[str, Any]]):
    # 1) Grab already-formatted training text
    texts = [ex["text"].strip() for ex in examples]

    # 2) Tokenize (TEXT ONLY)
    batch = processor(
        text=texts,
        return_tensors="pt",
        padding=True,
        truncation=True,   # important to avoid very long samples breaking batches
    )

    # 3) Labels = input_ids, with PAD masked out
    labels = batch["input_ids"].clone()
    labels[labels == processor.tokenizer.pad_token_id] = -100

    batch["labels"] = labels
    return batch

import torch
from transformers import TrainingArguments

num_train_epochs = 1
learning_rate = 2e-4

# bf16 only if GPU supports it, else fp16
major_cc, _ = torch.cuda.get_device_capability()
use_bf16 = major_cc >= 8

training_args = TrainingArguments(
    output_dir="medgemma-4b-it-lora-text",
    num_train_epochs=num_train_epochs,

    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,

    gradient_checkpointing=True,


    logging_steps=50,
    save_strategy="epoch",
    optim="paged_adamw_8bit",

    eval_strategy="no",
    eval_steps=50,

    learning_rate=learning_rate,
    bf16=use_bf16,
    fp16=not use_bf16,

    max_grad_norm=0.3,
    warmup_ratio=0.03,
    lr_scheduler_type="linear",

    report_to=["tensorboard"],

    remove_unused_columns=False,
    label_names=["labels"],

    # optional, keep off unless you’re sure you want it
    push_to_hub=False,
)

import torch
from peft import get_peft_model, prepare_model_for_kbit_training

# 1) Prepare quantized model for training (VERY important for 4-bit)
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_A,
    eval_dataset=val_A.shuffle(seed=42).select(range(200)),
    data_collator=collate_fn,
)

trainer.train()

trainer.save_model("lora_adapter")  # saves LoRA adapter + config
processor.tokenizer.save_pretrained("lora_adapter")

from google.colab import drive
drive.mount("/content/drive")

trainer.train(resume_from_checkpoint="PATH_TO_CHECKPOINT")

!pip uninstall -y transformers accelerate bitsandbytes peft huggingface_hub
!pip install -U \
  "transformers>=4.45.0" \
  "accelerate>=0.30.0" \
  "bitsandbytes>=0.46.1" \
  "peft>=0.11.0" \
  "huggingface_hub>=0.23.0"

!pip install -U bitsandbytes

import torch
import transformers
import accelerate
import bitsandbytes
import peft

from transformers import AutoTokenizer, AutoModelForCausalLM

print("Torch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)
print("BitsAndBytes:", bitsandbytes.__version__)
print("PEFT:", peft.__version__)

import torch
from transformers import AutoModelForCausalLM

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

!nvidia-smi