# -*- coding: utf-8 -*-
"""AdapterB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/aiswaryarani/adapterb.956005a1-90bd-40ca-ba55-e620c63fcf23.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260310/auto/storage/goog4_request%26X-Goog-Date%3D20260310T050617Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7c4774e3850c2a8b284196dcea162618e586b4773ed49e7f65be19dca0652fb1ac51027ae38b26ee790b1621d17824afc57b6cec5f46887f74fac7669c1ad468211defa31373f529dca162631930f9c9b3b1bbfbeb51777b2b81fa74cac09226bd76393c749e9d6daef5c45da231e76d7446bf6e0ae32c62d5b0bbb63916dc39ea2a5d5ce2aceae794dfc601b3cd15d2fd326725c4caa77b41a55058e279d0ae0f78b0ee95726bc1fc609dcc5ac4426a495cd920a8ee77d4ddae4a7bc5647b08cbdde65c149dfe48e15e85ae964b4110b01fe006c86254318d3320630f8884ffcbac23160712562b05881bd98ee431e0edf287b903892bca12c7a5ac958b7a95
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

aiswaryarani_jsonl_file_path = kagglehub.dataset_download('aiswaryarani/jsonl-file')
aiswaryarani_adapter_path = kagglehub.dataset_download('aiswaryarani/adapter')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/datasets/aiswaryarani/jsonl-file'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

!pip -q install google-cloud-bigquery-storage

!pip -q install -U transformers accelerate peft bitsandbytes datasets

!pip -q uninstall -y pyarrow datasets
!pip -q install --no-cache-dir "pyarrow==15.0.2" "datasets==2.19.2"

import os
from datasets import load_dataset, concatenate_datasets

base_path = "/kaggle/input/datasets/aiswaryarani/jsonl-file/jsonl_for_txt"
file_category_map = {
    # Thyroid
    "dataset_hypo.jsonl": "thyroid",
    "dataset_hypo_bal.jsonl": "thyroid",

    # PCOS
    "pcos_medgemma_multitask.jsonl": "pcos",
    "pcos_medgemma_task.jsonl": "pcos",
    "pcos1.jsonl": "pcos",
    "pcoss_sur.jsonl": "pcos",

    # Endometriosis
    "task1_hormonal_morphologic_endometriosis (1).jsonl": "endometriosis",
    "task2_reproductive_endometriosis_probability.jsonl": "endometriosis",

    # Anemia
    "female_anemia_multi_template.jsonl": "anemia",

    # Gestational Diabetes
    "gestational_diabetes_medgemma (1).jsonl": "gestational_diabetes_risk",

    # Preeclampsia
    "preeclampsia_bp.jsonl": "preeclampsia_risk",

    # Menses Pattern
    "task_menses_pattern (1).jsonl": "menses_pattern",
    "task1_menses_pattern (1).jsonl": "menses_pattern",

    # Education
    "task3_menstrual_education (1).jsonl": "menses_awareness",
    "remedial_symptom_awaren.jsonl": "menses_awareness",
    "remedial_symptom_awaren (1).jsonl": "menses_awareness",

    # Risk / Recurrence (we classify under risk)
    "dataset1_risk.jsonl": "thyroid",
    "dataset1_recurrence.jsonl": "thyroid",

    # Hormone ratio (likely endocrine)
    "dataset_ratio.jsonl": "thyroid"
}

datasets_list = []

for file_name, category in file_category_map.items():
    path = os.path.join(base_path, file_name)

    if os.path.exists(path):
        ds = load_dataset("json", data_files=path)["train"]
        ds = ds.add_column("category", [category] * len(ds))
        datasets_list.append(ds)
        print(f"Loaded {file_name} → {category} ({len(ds)} samples)")
    else:
        print(f"File not found: {file_name}")

full_dataset = concatenate_datasets(datasets_list)

print("\nTotal merged samples:", len(full_dataset))

adapterB_categories = [
    "gestational_diabetes_risk",
    "preeclampsia_risk",
    "menses_pattern",
    "menses_awareness"
]


adapterB_dataset = full_dataset.filter(
    lambda x: x["category"] in adapterB_categories
)

from collections import Counter


print("\nAdapter B distribution:")
print(Counter(adapterB_dataset["category"]))

print("Adapter B size:", len(adapterB_dataset))

target_size_B = 2000

balanced_splits_B = []

for category in adapterB_categories:
    subset = adapterB_dataset.filter(lambda x: x["category"] == category)
    current_size = len(subset)

    print(f"{category} original size: {current_size}")

    if current_size > target_size_B:
        subset = subset.shuffle(seed=42).select(range(target_size_B))

    elif current_size < target_size_B:
        multiplier = target_size_B // current_size
        remainder = target_size_B % current_size

        oversampled = concatenate_datasets([subset] * multiplier)
        if remainder > 0:
            oversampled = concatenate_datasets([
                oversampled,
                subset.shuffle(seed=42).select(range(remainder))
            ])
        subset = oversampled

    print(f"{category} balanced size: {len(subset)}\n")
    balanced_splits_B.append(subset)

balanced_adapterB = concatenate_datasets(balanced_splits_B)

print("Final Balanced Adapter B Distribution:")
print(Counter(balanced_adapterB["category"]))
print("Total Balanced Size:", len(balanced_adapterB))

from datasets import Features, ClassLabel

unique_categories_b = balanced_adapterB.unique("category")
balanced_adapterB = balanced_adapterB.cast_column(
    "category", ClassLabel(names=sorted(unique_categories_b))
)

adapterB_split = balanced_adapterB.train_test_split(
    test_size=0.1,
    seed=42,
    stratify_by_column="category"
)

train_B = adapterB_split["train"]
val_B = adapterB_split["test"]

print("Adapter B train size:", len(train_B))
print("Adapter B val size:", len(val_B))

def format_example(example):
    if example["input"].strip() != "":
        text = f"""### Instruction:
{example['instruction']}

### Input:
{example['input']}

### Response:
{example['output']}"""
    else:
        text = f"""### Instruction:
{example['instruction']}

### Response:
{example['output']}"""
    return {"text": text}

train_B = train_B.map(format_example, remove_columns=train_B.column_names)
val_B = val_B.map(format_example, remove_columns=val_B.column_names)

print(train_B[0]["text"])

from kaggle_secrets import UserSecretsClient

user_secrets = UserSecretsClient()
HF_TOKEN = user_secrets.get_secret("HF_TOKEN")

print("HF_TOKEN loaded successfully")

import torch
from transformers import AutoProcessor, AutoModelForImageTextToText, BitsAndBytesConfig

model_id = "google/medgemma-4b-it"

bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,  # A100
    bnb_4bit_quant_storage=torch.uint8,     # saves VRAM
)

model = AutoModelForImageTextToText.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    attn_implementation="eager",
    quantization_config=bnb,
)

processor = AutoProcessor.from_pretrained(model_id)
processor.tokenizer.padding_side = "right"

# Key for training memory
model.config.use_cache = False

from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()
HF_TOKEN = user_secrets.get_secret("HF_TOKEN")

print("Token loaded:", HF_TOKEN[:6] + "..." + HF_TOKEN[-4:])

import torch
from transformers import AutoProcessor, AutoModelForImageTextToText, BitsAndBytesConfig
from kaggle_secrets import UserSecretsClient

HF_TOKEN = UserSecretsClient().get_secret("HF_TOKEN")

model_id = "google/medgemma-4b-it"

bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_storage=torch.uint8,
)

model = AutoModelForImageTextToText.from_pretrained(
    model_id,
    token=HF_TOKEN,                 # ✅ REQUIRED for gated models in Kaggle
    device_map="auto",
    torch_dtype=torch.bfloat16,
    attn_implementation="eager",
    quantization_config=bnb,
)

processor = AutoProcessor.from_pretrained(
    model_id,
    token=HF_TOKEN                  # ✅ do it here too
)

processor.tokenizer.padding_side = "right"
model.config.use_cache = False

from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model

peft_config = LoraConfig(
    r=4,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    target_modules="all-linear",
    task_type="CAUSAL_LM",
    modules_to_save=None,
)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

from transformers import TrainingArguments
OUT_DIR = "/kaggle/working/medgemma_lora1_run"
training_args = TrainingArguments(
    output_dir=OUT_DIR,

    # Let it run "forever" across sessions by resuming
    num_train_epochs=1,  # keep 1; you'll resume if interrupted

    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,  # effective batch 16

    gradient_checkpointing=True,
    optim="paged_adamw_8bit",

    bf16=True,
    fp16=False,

    learning_rate=2e-4,
    warmup_ratio=0.03,
    lr_scheduler_type="linear",
    max_grad_norm=0.3,

    logging_steps=20,

    # No eval for stability/compute
    eval_strategy="no",

    # THIS is what protects you from disconnect
    save_strategy="steps",
    save_steps=50,          # every ~50 steps
    save_total_limit=3,     # keep last 3 checkpoints only

    remove_unused_columns=False,
    label_names=["labels"],
    report_to=["tensorboard"],
    push_to_hub=False,
)

from transformers import Trainer
import os, glob

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_B,
    data_collator=collate_fn,
)

# Auto-resume if checkpoints exist
ckpts = sorted(glob.glob(os.path.join(OUT_DIR, "checkpoint-*")), key=lambda x: int(x.split("-")[-1]))
resume_path = ckpts[-1] if ckpts else None

trainer.train(resume_from_checkpoint=resume_path)

FINAL1_DIR = "/kaggle/working/medgemma_lora2_adapter"

# Save LoRA adapter weights
trainer.save_model(FINAL1_DIR)

# Save tokenizer
processor.tokenizer.save_pretrained(FINAL1_DIR)

print("Saved files:")
import os
print(os.listdir(FINAL1_DIR))

!zip -r lora_adapter.zip /kaggle/working/medgemma_lora2_adapter

!pwd
!ls
!ls /kaggle/working/

!ls -lh /kaggle/working/lora_adapter.zip

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/datasets/aiswaryarani/medgemma-lorab'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

ADAPTER_PATH = "/kaggle/input/adapter"  # change to correct name

print("Listing:", ADAPTER_PATH)
print(os.listdir(ADAPTER_PATH))

ADAPTER_PATH = "/kaggle/working/adapterB_450"

print(val_B.column_names)

# =========================
# 0) Imports + HF token
# =========================
import os, math
import torch
from kaggle_secrets import UserSecretsClient
from transformers import AutoProcessor, AutoModelForImageTextToText, BitsAndBytesConfig
from peft import PeftModel

HF_TOKEN = UserSecretsClient().get_secret("HF_TOKEN")
BASE_ID = "google/medgemma-4b-it"

# =========================
# 1) Load BASE MedGemma (4-bit)
# =========================
bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_storage=torch.uint8,
)

base_model = AutoModelForImageTextToText.from_pretrained(
    BASE_ID,
    token=HF_TOKEN,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    attn_implementation="eager",
    quantization_config=bnb,
)
base_model.eval()

processor = AutoProcessor.from_pretrained(
    BASE_ID,
    token=HF_TOKEN
)

tokenizer = processor.tokenizer
tokenizer.padding_side = "right"
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print("✅ Base model + tokenizer loaded")

# =========================
# 2) Load Adapter B (450)
# =========================
ADAPTER_PATH = "/kaggle/working/adapterB_450"
assert os.path.exists(ADAPTER_PATH), f"Adapter folder not found: {ADAPTER_PATH}"
assert os.path.exists(os.path.join(ADAPTER_PATH, "adapter_config.json")), "Missing adapter_config.json"
assert os.path.exists(os.path.join(ADAPTER_PATH, "adapter_model.safetensors")), "Missing adapter_model.safetensors"

model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model.eval()

print("✅ Adapter B (450) loaded")

# =========================
# 3) Eval helpers (loss only on RESPONSE)
# =========================
RESPONSE_TAG = "### Response:\n"

def make_eval_item(text, max_len=2048):
    enc = tokenizer(text, add_special_tokens=False, truncation=True, max_length=max_len)
    input_ids = enc["input_ids"]
    attn = enc["attention_mask"]

    idx = text.find(RESPONSE_TAG)
    if idx == -1:
        # fallback: score all tokens
        labels = input_ids.copy()
    else:
        prompt_text = text[: idx + len(RESPONSE_TAG)]
        prompt_ids = tokenizer(prompt_text, add_special_tokens=False).input_ids
        labels = [-100]*len(prompt_ids) + input_ids[len(prompt_ids):]
        labels = labels[:len(input_ids)]

    return {
        "input_ids": torch.tensor(input_ids, dtype=torch.long),
        "attention_mask": torch.tensor(attn, dtype=torch.long),
        "labels": torch.tensor(labels, dtype=torch.long),
    }

def collate_pad(features):
    maxlen = max(f["input_ids"].shape[0] for f in features)

    def pad(x, value):
        return torch.nn.functional.pad(x, (0, maxlen - x.shape[0]), value=value)

    input_ids = torch.stack([pad(f["input_ids"], tokenizer.pad_token_id) for f in features])
    attention_mask = torch.stack([pad(f["attention_mask"], 0) for f in features])
    labels = torch.stack([pad(f["labels"], -100) for f in features])

    return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}

def evaluate_on_val(model, val_ds, batch_size=2, max_len=2048):
    losses = []
    with torch.no_grad():
        for i in range(0, len(val_ds), batch_size):
            batch_texts = val_ds[i:i+batch_size]["text"]
            feats = [make_eval_item(t, max_len=max_len) for t in batch_texts]
            batch = collate_pad(feats)
            batch = {k: v.to(model.device) for k, v in batch.items()}
            out = model(**batch)
            losses.append(out.loss.detach().float().item())

    mean_loss = sum(losses) / len(losses)
    ppl = math.exp(mean_loss) if mean_loss < 50 else float("inf")
    return mean_loss, ppl

# =========================
# 4) RUN EVALUATION
# =========================
# IMPORTANT: change val_B to your dataset variable name if different (val_A etc.)
mean_loss, ppl = evaluate_on_val(model, val_B, batch_size=2, max_len=2048)

print("Val samples:", len(val_B))
print("Val loss:", round(mean_loss, 4))
print("Val perplexity:", round(ppl, 3))

# =========================
# 5) Quick GENERATION sanity check (1 sample)
# =========================
def generate_from_val_text(model, full_text, max_new_tokens=180):
    prompt_only = full_text.split(RESPONSE_TAG, 1)[0] + RESPONSE_TAG
    inputs = tokenizer(prompt_only, return_tensors="pt").to(model.device)

    with torch.no_grad():
        gen = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            repetition_penalty=1.12,
            no_repeat_ngram_size=4,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    decoded = tokenizer.decode(gen[0], skip_special_tokens=True)
    resp = decoded.split("### Response:", 1)[-1].strip()

    # stop if it starts reprinting the prompt
    for marker in ["### Instruction:", "### Input:"]:
        if marker in resp:
            resp = resp.split(marker, 1)[0].strip()

    return resp

print("\n--- SAMPLE GENERATION ---")
print(generate_from_val_text(model, val_B[0]["text"], max_new_tokens=200))

