# -*- coding: utf-8 -*-
"""imgadapteripynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTSG6vfLs6Hj1n_GwCedwLIiOIUI34VA
"""

!pip install -q transformers datasets peft accelerate bitsandbytes evaluate rouge_score sacrebleu

!pip uninstall -y bitsandbytes
!pip install -U bitsandbytes>=0.46.1
!pip install -U transformers accelerate peft

!pip install --upgrade --quiet \
    torch torchvision torchaudio \
    bitsandbytes datasets evaluate peft tensorboard \
    transformers trl accelerate

from google.colab import drive
drive.mount('/content/drive')







from datasets import load_dataset, Image, concatenate_datasets, DatasetDict
import os

DATA_ROOTS = {
    "pcos":     "/content/drive/MyDrive/ovary_img_dir",
    "thyroid":  "/content/drive/MyDrive/dataset_split_thyroid",
    "mammograph": "/content/drive/MyDrive/basedir/mias_split_299"
}

JSONL_FILES = {
    "pcos":     "/content/drive/MyDrive/ovary_img_dir/pcos_fixed (1).jsonl",
    "thyroid":  "/content/drive/MyDrive/dataset_split_thyroid/thyroid_multimodal.jsonl",
    "mammograph": "/content/drive/MyDrive/basedir/mias_all.jsonl"
}

IMAGE_KEY = "image"

HAS_SPLIT_FIELD = False
SPLIT_KEY = "split"

PROMPTS = {
    "pcos": "Analyze this ovarian ultrasound for features of PCOS.",
    "thyroid": "Describe findings in this thyroid ultrasound image.",
    "mammograph": "Report any abnormalities or BI-RADS category in this mammogram."
}
# =======================================================

def load_one_dataset(name: str):
    root = DATA_ROOTS[name]
    json_path = os.path.join(root, JSONL_FILES[name])

    # Load jsonl
    ds = load_dataset("json", data_files=json_path, split="train")

    # Cast image column to PIL (with base directory awareness)
    def add_full_path(example):
        image_found = False
        for message in example.get("messages", []):
            if message.get("role") == "user" and "content" in message:
                for content_item in message["content"]:
                    if content_item.get("type") == "image" and "image_url" in content_item:
                        rel_path = content_item["image_url"]
                        full_path = os.path.join(root, rel_path)
                        example["image_path"] = full_path
                        image_found = True
                        break # Found the image, exit content loop
            if image_found:
                break # Found the image, exit messages loop
        return example

    ds = ds.map(add_full_path)
    ds = ds.cast_column("image_path", Image())   # this loads PIL images
    ds = ds.rename_column("image_path", "image") # now standard "image" column

    # Optional: if your json already has train/val/test marker
    if HAS_SPLIT_FIELD:
        splits = ds.train_test_split(test_size=0.0, stratify_by=SPLIT_KEY) # dummy
        # You'd filter instead:
        train_ds = ds.filter(lambda x: x[SPLIT_KEY] == "train")
        val_ds   = ds.filter(lambda x: x[SPLIT_KEY] == "val")
        test_ds  = ds.filter(lambda x: x[SPLIT_KEY] == "test")
    else:
        # Manual split (stratified if you have labels)
        train_val_test = ds.train_test_split(test_size=0.15, seed=42)
        train_val      = train_val_test["train"].train_test_split(test_size=0.15/(1-0.15), seed=42)

        train_ds = train_val["train"]
        val_ds   = train_val["test"]
        test_ds  = train_val_test["test"]

    return DatasetDict({
        "train": train_ds,
        "validation": val_ds,
        "test": test_ds
    })


# Load all three
all_splits = {}
for name in DATA_ROOTS:
    ds_dict = load_one_dataset(name)
    all_splits[name] = ds_dict

# Now combine across datasets
full_train = concatenate_datasets([all_splits[n]["train"]       for n in all_splits])
full_val   = concatenate_datasets([all_splits[n]["validation"]  for n in all_splits])
full_test  = concatenate_datasets([all_splits[n]["test"]        for n in all_splits])

print(f"Combined → train: {len(full_train):,} | val: {len(full_val):,} | test: {len(full_test):,}")

import json

jsonl_file_path = '/content/drive/MyDrive/ovary_img_dir/pcos_fixed (1).jsonl'

try:
    with open(jsonl_file_path, 'r') as f:
        first_line = f.readline()
        if first_line:
            example_data = json.loads(first_line)
            print(f"Keys in the first entry of {jsonl_file_path}: {list(example_data.keys())}")
        else:
            print(f"The file {jsonl_file_path} is empty.")
except FileNotFoundError:
    print(f"Error: The file {jsonl_file_path} was not found. Please ensure the path is correct.")
except json.JSONDecodeError:
    print(f"Error: Could not decode JSON from the first line of {jsonl_file_path}. Is it a valid JSONL file?")

def format_to_medgemma_chat(example, dataset_name: str):
    prompt_text = PROMPTS[dataset_name]

    target = (
        example.get("answer")
        or example.get("diagnosis")
        or example.get("report")
        or example.get("caption")
        or example.get("label")
        or str(example)  # fallback
    )

    example["messages"] = [
        {
            "role": "user",
            "content": [
                {"type": "image"},
                {"type": "text", "text": prompt_text},
            ]
        },
        {
            "role": "assistant",
            "content": [{"type": "text", "text": target}],
        }
    ]
    return example


# Apply formatting (you can do it per-dataset before concat, or after)
def add_messages_to_split(split_ds, name):
    return split_ds.map(lambda ex: format_to_medgemma_chat(ex, name))
    full_train = full_train.map(lambda ex, idx: format_to_medgemma_chat(ex, list(DATA_ROOTS.keys())[idx % len(DATA_ROOTS)]), with_indices=True)

from huggingface_hub import login
import os

# Option 1: Use your HF token (get from https://huggingface.co/settings/tokens)
HF_TOKEN = "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" # Replace with your token
login(token=HF_TOKEN)

# Option 2: If token in env (Colab: add as secret)
# login(token=os.getenv("HF_TOKEN"))

import torch
from datasets import load_dataset, concatenate_datasets, Image
from peft import LoraConfig, get_peft_model,prepare_model_for_kbit_training
from trl import SFTConfig, SFTTrainer
from transformers import AutoProcessor, AutoModelForImageTextToText, BitsAndBytesConfig

PROMPTS = {
    "pcos": "What PCOS features are visible in this ovarian ultrasound image?",
    "thyroid": "Describe any thyroid abnormalities in this ultrasound image.",
    "mammograph": "What BI-RADS findings or abnormalities are present in this mammogram?"
}
# ===========================================
MODEL_ID = "google/medgemma-1.5-4b-it"   # or "google/medgemma-4b-it"
OUTPUT_DIR = "content/drive/Mydrive/medgemma-4b-lora-pcos-thyroid-mammo"
# 4-bit quantization + LoRA
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForImageTextToText.from_pretrained(
    MODEL_ID,
    quantization_config=quantization_config,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    attn_implementation="eager",
)

processor = AutoProcessor.from_pretrained(MODEL_ID)
processor.tokenizer.padding_side = "right"
model.config.use_cache = False
peft_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.03,
    target_modules="all-linear",
    bias="none",
    task_type="CAUSAL_LM",
    modules_to_save=None,
)

def format_to_medgemma_chat(example, dataset_name: str):
    prompt_text = PROMPTS[dataset_name]

    target = (
        example.get("answer")
        or example.get("diagnosis")
        or example.get("report")
        or example.get("caption")
        or example.get("label")
        or str(example)  # fallback
    )

    example["messages"] = [
        {
            "role": "user",
            "content": [
                {"type": "image"},
                {"type": "text", "text": prompt_text},
            ]
        },
        {
            "role": "assistant",
            "content": [{"type": "text", "text": target}],
        }
    ]
    return example


def add_messages_to_split(split_ds, name):
    return split_ds.map(lambda ex: format_to_medgemma_chat(ex, name))
    full_train = full_train.map(lambda ex, idx: format_to_medgemma_chat(ex, list(DATA_ROOTS.keys())[idx % len(DATA_ROOTS)]), with_indices=True)

def collate_fn(examples):
    texts = []
    images = []
    for ex in examples:
        # processor expects list of images per example
        images.append([ex["image"].convert("RGB")])
        text = processor.apply_chat_template(
            ex["messages"], add_generation_prompt=False, tokenize=False
        ).strip()
        texts.append(text)

    batch = processor(text=texts, images=images, return_tensors="pt", padding=True)

    labels = batch["input_ids"].clone()
    labels[labels == processor.tokenizer.pad_token_id] = -100

    # Mask image tokens
    boi_token_id = processor.tokenizer.convert_tokens_to_ids(
        processor.tokenizer.special_tokens_map["boi_token"]
    )
    labels[labels == boi_token_id] = -100

    batch["labels"] = labels
    return batch

import glob

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)

training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    num_train_epochs=1,
    per_device_train_batch_size=4,
    gradient_checkpointing=True,
    optim="paged_adamw_8bit",
    learning_rate=2e-4,
    bf16=True,
    max_grad_norm=0.3,
    warmup_steps=0.03,
    lr_scheduler_type="linear",
    logging_steps=10,
    eval_strategy="no",
    save_strategy="steps",
    save_steps=50,
    save_total_limit=3,
    push_to_hub=False,
    report_to="tensorboard",
    dataset_kwargs={"skip_prepare_dataset": True},
    remove_unused_columns=False,
    label_names=["labels"],
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=full_train,
    eval_dataset=full_train.shuffle(seed=42).select(range(500)),
    processing_class=processor,
    data_collator=collate_fn,
)


trainer.train()

FINAL_DIR = "/content/drive/MyDrive/medgemma_a100_img_adapter2"
trainer.save_model(FINAL_DIR)
processor.tokenizer.save_pretrained(FINAL_DIR)

###evaluation

import os
import torch
from peft import PeftModel

train_result = trainer.train()
trainer.save_state()

ADAPTER_DIR = os.path.join(OUTPUT_DIR, "lora_adapter")
os.makedirs(ADAPTER_DIR, exist_ok=True)
trainer.model.save_pretrained(ADAPTER_DIR)
processor.save_pretrained(ADAPTER_DIR)

print("Saved LoRA adapter + processor to:", ADAPTER_DIR)
eval_metrics = trainer.evaluate()
print("Eval metrics:", eval_metrics)

infer_model = trainer.model
infer_model.eval()


# processor = AutoProcessor.from_pretrained(ADAPTER_DIR)
# infer_model = PeftModel.from_pretrained(base, ADAPTER_DIR)
# infer_model.eval()

@torch.no_grad()
def generate_from_example(ex, max_new_tokens=256, temperature=0.2, top_p=0.9):
    # Build the exact same text format you trained on
    prompt = processor.apply_chat_template(
        ex["messages"],
        add_generation_prompt=True,   # IMPORTANT for inference
        tokenize=False
    ).strip()

    img = ex["image"].convert("RGB")
    inputs = processor(
        text=[prompt],
        images=[[img]],
        return_tensors="pt",
        padding=True
    )
    device = next(infer_model.parameters()).device
    inputs = {k: v.to(device) for k, v in inputs.items()}

    gen_ids = infer_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=(temperature is not None and temperature > 0),
        temperature=temperature,
        top_p=top_p,
        use_cache=True
    )
    out_text = processor.tokenizer.decode(gen_ids[0], skip_special_tokens=True)

    return out_text

small_eval = trainer.eval_dataset.select(range(min(20, len(trainer.eval_dataset))))

for i in range(len(small_eval)):
    pred = generate_from_example(small_eval[i], max_new_tokens=256, temperature=0.2)
    print("\n" + "="*80)
    print("Example:", i)
    print("PRED:\n", pred)

def extract_gold_assistant_text(messages):
    # find last assistant message that has "content"
    for m in reversed(messages):
        if m.get("role") == "assistant":
            c = m.get("content")
            if isinstance(c, str):
                return c.strip()
            # if content is list/structured, you can adapt here
            return str(c).strip()
    return None

def simple_exact_match(eval_ds, n=100):
    n = min(n, len(eval_ds))
    hit = 0
    total = 0
    for i in range(n):
        ex = eval_ds[i]
        gold = extract_gold_assistant_text(ex["messages"])
        if gold is None:
            continue
        pred = generate_from_example(ex, max_new_tokens=256, temperature=0.0)
        # very strict; you can loosen with contains/normalize if needed
        if pred.strip() == gold.strip():
            hit += 1
        total += 1
    return (hit / total) if total > 0 else None

em = simple_exact_match(trainer.eval_dataset, n=100)
print("Exact-match (strict) over up to 100 examples:", em)
MERGED_DIR = os.path.join(OUTPUT_DIR, "merged_model")
os.makedirs(MERGED_DIR, exist_ok=True)

try:
    merged = infer_model.merge_and_unload()
    merged.save_pretrained(MERGED_DIR, safe_serialization=True)
    processor.save_pretrained(MERGED_DIR)
    print("Saved merged model to:", MERGED_DIR)
except Exception as e:
    print("Merge failed (common with 4-bit base). Error:\n", str(e))
    print("If you want merging, reload the base model in bf16/fp16 (no 4-bit), then attach adapter, then merge.")

