# -*- coding: utf-8 -*-
"""RagsPlugin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fE8kxSQMu5eR9oLfYsJXdEzUzz8s2_Qb
"""

!pip install -q transformers datasets peft accelerate bitsandbytes evaluate rouge_score sacrebleu

!pip uninstall -y bitsandbytes
!pip install -U bitsandbytes>=0.46.1
!pip install -U transformers accelerate peft

from huggingface_hub import login
import os

# Option 1: Use your HF token (get from https://huggingface.co/settings/tokens)
HF_TOKEN = "" # Replace with your token
login(token=HF_TOKEN)

# Option 2: If token in env (Colab: add as secret)
# login(token=os.getenv("HF_TOKEN"))

import torch
from transformers import AutoProcessor, AutoModelForImageTextToText, BitsAndBytesConfig
from peft import PeftModel
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import gradio as gr

BASE_ID = "google/medgemma-4b-it"

bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

# Load base model once
base_model = AutoModelForImageTextToText.from_pretrained(
    BASE_ID,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    attn_implementation="eager",
    quantization_config=bnb,
)
base_model.eval()

processor = AutoProcessor.from_pretrained(BASE_ID)
tokenizer = processor.tokenizer
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Load Adapter A and B
ADAPTER_A_PATH = "/content/drive/MyDrive/medgemma_a100_lora_adapter"
ADAPTER_B_PATH = "/content/drive/MyDrive/adapter_B"

model = PeftModel.from_pretrained(base_model, ADAPTER_A_PATH, adapter_name="Adapter_A")
model.load_adapter(ADAPTER_B_PATH, adapter_name="Adapter_B")

model.set_adapter("Adapter_A")
model.eval()

print("Adapters loaded successfully")



from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

class ClinicalRAG:
    def __init__(self, filepath):
        with open(filepath, "r", encoding="utf-8") as f:
            text = f.read()

        self.chunks = [chunk.strip() for chunk in text.split("SECTION") if chunk.strip()]
        self.vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
        self.tfidf = self.vectorizer.fit_transform(self.chunks)

    def retrieve(self, query, top_k=3):
        q_vec = self.vectorizer.transform([query])
        sims = cosine_similarity(q_vec, self.tfidf).flatten()
        idxs = sims.argsort()[::-1][:top_k]
        return "\n\n".join([self.chunks[i] for i in idxs])

rag = ClinicalRAG("/content/ragsrules.txt")

RESPONSE_TAG = "### Response:\n"

def build_prompt(instruction, inp, use_rag=True):
    rules = rag.retrieve(instruction + " " + inp) if use_rag else ""

    return f"""### Instruction:
{instruction}

### Input:
{inp}

### Retrieved Clinical Rules:
{rules}

### Response:
"""

@torch.no_grad()
def generate_answer(adapter_name, instruction, inp, use_rag, max_new_tokens):

    model.set_adapter(adapter_name)

    prompt = build_prompt(instruction, inp, use_rag)
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    gen = model.generate(
        **inputs,
        max_new_tokens=int(max_new_tokens),
        do_sample=False,
        repetition_penalty=1.15,
        no_repeat_ngram_size=4,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id,
    )

    decoded = tokenizer.decode(gen[0], skip_special_tokens=True)
    response = decoded.split("### Response:", 1)[-1].strip()

    return response

import traceback

def generate_answer_safe(adapter_name, instruction, inp, use_rag, max_new_tokens):
    try:
        return generate_answer(adapter_name, instruction, inp, use_rag, max_new_tokens)
    except Exception as e:
        tb = traceback.format_exc()
        return f"❌ ERROR:\n{str(e)}\n\nTRACEBACK:\n{tb}"

from google.colab import drive
drive.mount('/content/drive')

import gradio as gr
from datetime import datetime

THEME = gr.themes.Soft(
    primary_hue="violet",
    secondary_hue="pink",
    neutral_hue="slate",
    font=["Inter", "ui-sans-serif", "system-ui", "Segoe UI", "Roboto"]
)

CUSTOM_CSS = """
.gradio-container { max-width: 1100px !important; }
#title { font-size: 30px; font-weight: 900; letter-spacing: -0.7px; }
#subtitle { opacity: 0.85; font-size: 13px; margin-top: 6px; }
.card {
  border-radius: 18px !important;
  border: 1px solid rgba(255,255,255,0.08) !important;
  background: rgba(255,255,255,0.02) !important;
  box-shadow: 0 10px 30px rgba(0,0,0,0.20) !important;
}
.badge{
  display:inline-flex; gap:8px; align-items:center;
  padding:8px 12px; border-radius:999px;
  background: rgba(168,85,247,0.12);
  border: 1px solid rgba(168,85,247,0.25);
  font-size:12px; font-weight:700;
  margin-right: 10px;
}
#run_btn { height: 44px; font-weight: 800; border-radius: 12px; }
#out textarea {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace !important;
  font-size: 13px !important;
}
"""

# --- test presets ---
PCOS_SAMPLE = """FSH/LH ratio: 1.25
Waist-Hip Ratio: 0.88
AMH (ng/mL): 6.2
Total Follicle Count: 22
Endometrial Thickness (mm): 7.6
BMI: 29.4
Symptoms: acne, mild hirsutism"""

ENDO_SAMPLE = """Menstrual cycle pattern (0=regular, 1=irregular): 1
Serum testosterone level (ng/dL): 58.0
Antral follicle count (AFC): 14
Pelvic pain: moderate
Dyspareunia: present"""

LIFESTYLE_SAMPLE = """Age: 22
BMI: 27.8
Stress Level (1–5): 4
Exercise Frequency: Low
Sleep Hours: 5.5
Diet: High refined carbs
Cycle Length: 38 days
Period Length: 6 days
Symptoms: fatigue, acne"""

THYROID_SAMPLE = """TSH (mIU/L): 6.1
Free T4 (ng/dL): 0.92
TPO antibodies: positive
Symptoms: fatigue, weight gain
Pregnancy status: not pregnant"""

def preset_to_text(name):
    if "PCOS" in name: return PCOS_SAMPLE
    if "Endometriosis" in name: return ENDO_SAMPLE
    if "Lifestyle" in name: return LIFESTYLE_SAMPLE
    return THYROID_SAMPLE

# Use real adapter keys dynamically (prevents mismatch)
adapter_keys = list(model.peft_config.keys())  # IMPORTANT
default_adapter = adapter_keys[0] if adapter_keys else None

with gr.Blocks(theme=THEME, css=CUSTOM_CSS, title="FEMINA — UI") as demo:
    gr.HTML(f"""
    <div>
      <div id="title">FEMINA</div>
      <div id="subtitle">MedGemma + LoRA Adapters + Rulebook RAG • structured, non-diagnostic reasoning</div>
      <div style="margin-top:12px;">
        <span class="badge">🧠 MedGemma-4B</span>
        <span class="badge">🧩 Multi-Adapter</span>
        <span class="badge">📚 RAG Rulebook</span>
        <span class="badge">🛡️ Safety</span>
        <span style="opacity:.75; font-size:12px; float:right;">{datetime.now().strftime("%d %b %Y • %I:%M %p")}</span>
      </div>
    </div>
    """)

    with gr.Row():
        with gr.Column(scale=5):
            with gr.Group(elem_classes="card"):
                adapter_choice = gr.Dropdown(
                    choices=adapter_keys,
                    value=default_adapter,
                    label="Select Adapter"
                )
                use_rag = gr.Checkbox(value=True, label="Use Clinical Rulebook (RAG)")
                instruction = gr.Textbox(
                    lines=3,
                    label="Instruction",
                    value="Provide structured clinical reasoning without giving a definitive diagnosis."
                )

            with gr.Group(elem_classes="card"):
                clinical_input = gr.Textbox(lines=10, label="Clinical Input", placeholder="Paste patient profile / labs / symptoms…")
                max_tokens = gr.Slider(60, 450, value=200, step=10, label="Max new tokens")

                with gr.Row():
                    run_btn = gr.Button("Generate", variant="primary", elem_id="run_btn")
                    clear_btn = gr.Button("Clear", variant="secondary")

            with gr.Accordion("Quick test presets", open=False):
                preset = gr.Radio(
                    ["Menstrual + Lifestyle", "PCOS / Androgen + Morphology", "Endometriosis-style profile", "Thyroid profile"],
                    value="Menstrual + Lifestyle",
                    label="Choose preset"
                )
                apply_btn = gr.Button("Apply preset")

        with gr.Column(scale=6):
            with gr.Group(elem_classes="card"):
                output = gr.Textbox(lines=18, label="Model Output", elem_id="out")

    run_btn.click(
        fn=generate_answer_safe,   # wrapper prevents UI crash and prints traceback
        inputs=[adapter_choice, instruction, clinical_input, use_rag, max_tokens],
        outputs=output
    )

    clear_btn.click(lambda: ("", ""), outputs=[clinical_input, output])

    apply_btn.click(lambda p: preset_to_text(p), inputs=preset, outputs=clinical_input)

demo.launch(share=True, debug=True)